version: '3.7'
services:
  client:
    build: .
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - api
